back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /admin

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# Route De commur Image
comur_image:
    resource: "@ComurImageBundle/Resources/config/routing.yml"
    prefix:   /

